export const GET_FIRST_FORM_DATA = "GET_FIRST_FORM_DATA";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAILED = "CREATE_JOB_FAILED";

export const GET_JOB_DETAILS_REQUEST = "GET_JOB_DETAILS_REQUEST";
export const GET_JOB_DETAILS_SUCCESS = "GET_JOB_DETAILS_SUCCESS";
export const GET_JOB_DETAILS_FAILED = "GET_JOB_DETAILS_FAILED";

export const DELETE_JOB_DETAILS_REQUEST = "DELETE_JOB_DETAILS_REQUEST";
export const DELETE_JOB_DETAILS_SUCCESS = "DELETE_JOB_DETAILS_SUCCESS";
export const DELETE_JOB_DETAILS_FAILED = "DELETE_JOB_DETAILS_FAILED";

export const GET_SINGLE_JOB_DETAIL_REQUEST = "GET_SINGLE_JOB_DETAIL_REQUEST";
export const GET_SINGLE_JOB_DETAIL_SUCCESS = "GET_SINGLE_JOB_DETAIL_SUCCESS";
export const GET_SINGLE_JOB_DETAIL_FAILED = "GET_SINGLE_JOB_DETAIL_FAILED";

export const UPDATE_JOB_DETAIL_REQUEST = "UPDATE_JOB_DETAIL_REQUEST";
export const UPDATE_JOB_DETAIL_SUCCESS = "UPDATE_JOB_DETAIL_SUCCESS";
export const UPDATE_JOB_DETAIL_FAILED = "UPDATE_JOB_DETAIL_FAILED";